#!/bin/bash
set -ex

docker image build \
    --build-arg username=insecurit \
    --build-arg uid=1000 \
    --build-arg gid=100 \
    --tag "docker-project-template:latest" \
    --file Dockerfile \
    ../
