#!/bin/bash
set -ex

docker image build \
    --build-arg username=insecurit \
    --build-arg uid=1001 \
    --build-arg gid=101 \
    --tag "docker-project-template:latest" \
    --file Dockerfile \
    ../
